## In Class Activity 1

Osaka, Japan is located at:

    34.6937° N, 135.5023° E
    
1. Create a dataframe of the next 24 hours of their weather as was done above
2. Make a function `get_forecast` which accepts:
    - `lat`
    - `lon`
    - `api_key`
    - `units` (default = 'imperial')
    
    and returns a dataframe of the next 24 hours of the location's weather.

In [1]:
import requests
import json
import pandas as pd
from datetime import datetime

# input arguments to API (these define our query)
# north = positive, south = negative
lat = 34.6937

# west = positive, east = negative
lon = -135.5023

# api key
api_key = 'a09fbc60af08d36a8942789ae2864dab'


def get_forecast(lat, lon, 
                 api_key='a09fbc60af08d36a8942789ae2864dab', 
                 units='imperial'):
    
    # build url
    url = f'https://api.openweathermap.org/data/2.5/onecall?lat={lat}&lon={lon}&appid={api_key}&units={units}'
    print(url)

    # get url response as a string
    url_text = requests.get(url).text

    # convert from json to a nested dict
    weather_dict = json.loads(url_text)

    # build dataframe from nested dict
    df_daily = pd.DataFrame()
    for day_dict in weather_dict['daily']:
        
        # we add a 'datetime' feature from the unix time (easier to use)
        day_dict['datetime'] = datetime.fromtimestamp(day_dict['dt'])

        # build a single row of dataframe (weather prediction for some hour)
        s_day = pd.Series(day_dict)

        # collect forecasts in a dataframe
        df_daily = df_daily.append(s_day, ignore_index=True)

    return df_daily.head()

get_forecast(lat, lon)

https://api.openweathermap.org/data/2.5/onecall?lat=34.6937&lon=-135.5023&appid=a09fbc60af08d36a8942789ae2864dab&units=imperial

,dt,sunrise,sunset,moonrise,moonset,moon_phase,temp,feels_like,pressure,humidity,dew_point,wind_speed,wind_deg,wind_gust,weather,clouds,pop,uvi,datetime,rain
0,1.644959e+09,1.644940e+09,1.644979e+09,1.644977e+09,1.644939e+09,0.47,"{'day': 56.08, 'min': 56.08, 'max': 58.1, 'nig...","{'day': 54.88, 'night': 55.67, 'eve': 55.45, '...",1031.0,74.0,47.84,20.85,28.0,22.26,"[{'id': 804, 'main': 'Clouds', 'description': ...",100.0,0.0,2.57,2022-02-15 16:00:00,NaN
1,1.645045e+09,1.645026e+09,1.645066e+09,1.645067e+09,1.645028e+09,0.50,"{'day': 58.24, 'min': 57.02, 'max': 58.91, 'ni...","{'day': 57.25, 'night': 57.6, 'eve': 57.79, 'm...",1034.0,74.0,50.11,22.32,51.0,24.99,"[{'id': 800, 'main': 'Clear', 'description': '...",4.0,0.0,4.85,2022-02-16 16:00:00,NaN
2,1.645132e+09,1.645113e+09,1.645152e+09,1.645157e+09,1.645116e+09,0.54,"{'day': 57.34, 'min': 57.15, 'max': 58.39, 'ni...","{'day': 56.68, 'night': 56.77, 'eve': 56.91, '...",1033.0,83.0,52.02,21.05,38.0,23.91,"[{'id': 804, 'main': 'Clouds', 'description': ...",100.0,0.0,2.54,2022-02-17 16:00:00,NaN
3,1.645218e+09,1.645199e+09,1.645239e+09,1.645247e+09,1.645204e+09,0.57,"{'day': 57.49, 'min': 57.04, 'max': 58.33, 'ni...","{'day': 56.64, 'night': 57.58, 'eve': 57.43, '...",1030.0,79.0,51.06,19.01,75.0,20.36,"[{'id': 500, 'main': 'Rain', 'description': 'l...",100.0,0.2,2.92,2022-02-18 16:00:00,0.13
4,1.645304e+09,1.645285e+09,1.645325e+09,1.645337e+09,1.645292e+09,0.61,"{'day': 58.98, 'min': 58.21, 'max': 58.98, 'ni...","{'day': 58.1, 'night': 57.4, 'eve': 57.78, 'mo...",1027.0,75.0,51.06,18.05,77.0,19.35,"[{'id': 804, 'main': 'Clouds', 'description': ...",100.0,0.0,3.00,2022-02-19 16:00:00,NaN

In [2]:
# get the forecast of Shrewsbury, MA
get_forecast(42.2959, 71.7128)

https://api.openweathermap.org/data/2.5/onecall?lat=42.2959&lon=71.7128&appid=a09fbc60af08d36a8942789ae2864dab&units=imperial

,dt,sunrise,sunset,moonrise,moonset,moon_phase,temp,feels_like,pressure,humidity,dew_point,wind_speed,wind_deg,wind_gust,weather,clouds,pop,uvi,datetime
0,1.644908e+09,1.644891e+09,1.644929e+09,1.644924e+09,1.644890e+09,0.45,"{'day': 13.84, 'min': 0.64, 'max': 13.84, 'nig...","{'day': 5.18, 'night': -5.8, 'eve': -7.89, 'mo...",1030.0,73.0,3.31,14.58,199.0,16.53,"[{'id': 804, 'main': 'Clouds', 'description': ...",100.0,0.31,1.97,2022-02-15 02:00:00
1,1.644995e+09,1.644977e+09,1.645016e+09,1.645014e+09,1.644978e+09,0.50,"{'day': 12.69, 'min': 0.93, 'max': 14.04, 'nig...","{'day': 12.69, 'night': -10.88, 'eve': -7.04, ...",1029.0,72.0,1.60,9.15,197.0,9.51,"[{'id': 801, 'main': 'Clouds', 'description': ...",17.0,0.24,2.78,2022-02-16 02:00:00
2,1.645081e+09,1.645064e+09,1.645102e+09,1.645104e+09,1.645066e+09,0.52,"{'day': 17.67, 'min': 1.29, 'max': 18.91, 'nig...","{'day': 17.67, 'night': -8.1, 'eve': -6.59, 'm...",1028.0,44.0,-3.95,10.74,188.0,8.41,"[{'id': 800, 'main': 'Clear', 'description': '...",0.0,0.00,2.86,2022-02-17 02:00:00
3,1.645168e+09,1.645150e+09,1.645189e+09,1.645195e+09,1.645154e+09,0.55,"{'day': 24.01, 'min': 4.24, 'max': 25.52, 'nig...","{'day': 19.72, 'night': -0.2, 'eve': 10.74, 'm...",1023.0,43.0,2.53,10.94,190.0,8.68,"[{'id': 800, 'main': 'Clear', 'description': '...",0.0,0.00,2.64,2022-02-18 02:00:00
4,1.645254e+09,1.645236e+09,1.645275e+09,1.645285e+09,1.645242e+09,0.58,"{'day': 27.99, 'min': 12.2, 'max': 29.43, 'nig...","{'day': 24.75, 'night': 5.74, 'eve': 21.96, 'm...",1019.0,46.0,7.18,10.54,192.0,8.59,"[{'id': 802, 'main': 'Clouds', 'description': ...",37.0,0.00,2.53,2022-02-19 02:00:00

## In Class Activity 2
1. Write a function `from_unix_to_datetime()` which:
- accepts:
    - unix_time (float): time since jan 1 1970 (in computer's time zone)
    - timezone_from (str): timezone of input unix_time ('uct' by default)
    - timezone_to (str): timezone of output datetime object
- returns:
    - datetime_tz (datetime): datetime object in given timezone
Be sure to properly document your function.
2.  Write a few `assert` test cases to validate your function.
    - Rather than checking if values are proper yourself, it may be best to rely on [another source](https://www.epochconverter.com/)

In [3]:
import requests
import json
from datetime import datetime, date, time
import pytz

def from_unix_to_datetime(unix_time, timezone_to='US/Eastern'):
    """ converts unix time to datetime object
    
    Args: 
        unix_time (float): unix time (sec since jan 1 1970 UTC)
        timezone_to (str): timezone of output datetime object
        
    Returns:
        datetime_tz (datetime): datetime object in given timezone
    """
    
    # build datetime
    datetime_from = datetime.utcfromtimestamp(unix_time)
    
    # add timezone to datetime
    tz_from = pytz.timezone('UTC')
    datetime_from = tz_from.localize(datetime_from)
    
    # convert timezone
    tz_to = pytz.timezone(timezone_to)
    dt = datetime_from.astimezone(tz_to)
    
    return dt

In [4]:
# test case

unix_time = 1644940967
timezone_to = 'US/Eastern'

from_unix_to_datetime(unix_time=1644940967, timezone_to='US/Eastern')

datetime_computed = from_unix_to_datetime(unix_time=1644940967, timezone_to='US/Eastern')

time_zone = pytz.timezone(timezone_to)

datetime_expected = time_zone.localize(datetime(2022, 2, 15, 11, 2, 47))

assert datetime_expected == datetime_computed

# In Class Activity 3

Write a few 'empty' functions including little more than the docstring:

```python
def some_fnc(a_string, a_list):
    """ processes a string and a list (somehow)
    
    Args:
        a_string (str): an input string which ...
        a_list (list): a list which describes ...
        
    Returns:
        output (dict): the output dict which is ...
    """
    pass
```

and a script which uses them:

```python
# inputs (not necessarily complete)
lat = -42
lon = 73

some_output = some_fnc(lat, lon)
some_other_output = some_other_fnc(some_output)

```

which would, if the functions worked, produce the following graph:

<img src="https://i.ibb.co/8j6VqqG/scatter.png" width=500\img>

In [5]:
# did not get to it in class